### ISSUE TITLE
Boat State Handler Base

### ISSUE THREAD

**Issue by 1unarzDev** [MHSeals/mhsboat_ctrl#34]
This is the bulk of what needs to be done for us to get points and qualify for comp. Using the [list of tasks](https://robonation.gitbook.io/roboboat-resources/section-3-autonomy-challenge/3.2-task-descriptions), we need to determine what course of action is best for the boat. We should avoid being soft-locked at all costs. If the boat is stuck on a task, transition to the next thing. If we have a task with a high success rate, prioritize it.

**Comment by bryanchan407** [comment]
alec should have a good base on a boat state handler... closed for now.
